apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lscsde
resources: []
configMapGenerator:
  - name: aks-dns-operator-config
    files:
      - values.yaml=aks-dns-operator-config.yaml
generatorOptions:
  disableNameSuffixHash: true
