apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: configmap-transformer-controller
  annotations:
    lsc-sde.nhs.uk/definitionVersion: "1.0.1"
spec:
  targetNamespace: lscsde
  releaseName: configmap-transformer-controller
  chart:
    spec:
      chart: configmap-transformer-controller
      sourceRef:
        kind: HelmRepository
        name: lsc-sde
        namespace: lscsde
  interval: 5m0s
  install:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  upgrade:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
