apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-config
data:
  environment_name: production
  
  ohdsi_branch: main 
  ohdsi_chart_version: "0.1.2"
  
  secrets_distributor_chart_version: "0.1.2"

  certmanager_branch: "release/0.1.20"
  certmanager_chart_version: "v1.14.2"
  trustmanager_chart_version: "0.8.0"
  
  github_runner_branch: "release/0.1.47"
  github_runner_chart_version: "0.1.17"
  
  aks_dns_branch: main
  aks_dns_chart_version: "0.1.7"
  
  configmap_transformer_branch: main
  configmap_transformer_chart_version: "0.1.0"

  nginx_branch: "release/0.1.43"
  nginx_chart_version: "4.9.1"
  
  keda_branch: "release/0.1.30"
  keda_chart_version: "2.13.1"

  keycloak_branch: "release/0.1.56"

  jupyter_branch: "release/0.2.15"
  jupyter_chart_version: "3.2.1"

  analytics_workspace_management_chart_version: "0.1.1"
  analytics_workspace_management_branch: "main"
